library(dplyr)
library(ggplot2)
library(gridExtra)
library(tibble)
library(stringi)
library(ggiraph)
library(devtools)
library(ggiraphExtra)
library(kormaps2014)
library(plotly)
library(dygraphs)
library(xts)

load('data/kdata.rda')
load('data/data_eng.rda')
